<h1>Signature Code</h1>
<p>Follow the instructions sent to you by email to copy this code into the right part of your mail client's signature
    file. This may differ for certain email clients. Remember to ask if you have a unique unlisted case. </p>
</div>
<div class="card-dark no-shadow no-margin small-pad">
                    <pre><code>
&lt;span style="font-family: 'Lato', Arial, sans-serif; font-size:0.8rem; font-weight: 400; line-height: 1.1rem; letter-spacing:.1rem; color: #776869 !important; "&gt;&lt;b&gt;{{ $name ?? '' }}&lt;/b&gt;&lt;br&gt;&lt;i&gt;{{ $title ?? '' }}&lt;/i&gt;&lt;br&gt;&lt;a href="tel:+91{{ $phone ?? '' }}" style="color:#776869 !important; text-decoration:none !important;"&gt;m: {{ $phone ?? '' }}&lt;/a&gt; &lt;hr style="border-top:0.5px solid #776869; display:block; clear:both;"&gt;&lt;img src="http://ajitshilpi.com/AjitShilpi-01.png" style="float:left; clear:left; height:5rem;  margin-right:0.7rem; margin-bottom:0.5rem;"&gt;&lt;span style="float:left; clear:right;  margin-bottom:0.5rem; border-left:0.5px solid #776869; padding-left:.5rem; min-height:5rem; width:calc(100% - 5rem); overflow:auto;"&gt; &lt;span style="text-transform:uppercase;"&gt;AJIT&lt;span style="font-weight:900;"&gt;SHILPI&lt;/span&gt; &nbsp; Architecture + Interiors&lt;/span&gt;
&lt;br&gt; #9 Raghuvanshi Estate, Senapati Bapat Marg, Lower Parel, Mumbai 400013 &lt;br&gt; &lt;a href="tel:+912224992499" style="color:#776869 !important; text-decoration:none !important;"&gt;t: +91 22 2499 2499&lt;/a&gt; &lt;a href="http://www.ajitshilpi.com/" style="color:#776869 !important; text-decoration:none !important;"&gt;www.ajitshilpi.com&lt;/a&gt; &lt;/span&gt; &lt;hr style="border-top:0.5px solid #776869; display:block; clear:both;"&gt;&lt;/span&gt;
                    </code></pre>
</div>